
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banner_clicks
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d banner_clicks"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: banner_clicks
      DB_SSLMODE: disable
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  db_data: